In [8]:
import pandas as pd

In [14]:
df_cars = pd.read_csv('C:/Users/shama/PycharmProjects/thesis/data/car_evaluation/car.data', names=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'acceptability'])
df_cars

     buying  maint  doors persons lug_boot safety acceptability
0     vhigh  vhigh      2       2    small    low         unacc
1     vhigh  vhigh      2       2    small    med         unacc
2     vhigh  vhigh      2       2    small   high         unacc
3     vhigh  vhigh      2       2      med    low         unacc
4     vhigh  vhigh      2       2      med    med         unacc
...     ...    ...    ...     ...      ...    ...           ...
1723    low    low  5more    more      med    med          good
1724    low    low  5more    more      med   high         vgood
1725    low    low  5more    more      big    low         unacc
1726    low    low  5more    more      big    med          good
1727    low    low  5more    more      big   high         vgood

[1728 rows x 7 columns]

In [18]:
df_cars.columns

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety',
       'acceptability'],
      dtype='object')

In [19]:
df_cars.to_csv('C:/Users/shama/PycharmProjects/thesis/data/car.csv')